### PR TITLE
Fix GraphQL syntax error in turbot_control data source

### LINKED ISSUE #233: GraphQL syntax error when querying turbot_control by type and resource
## Description

The `turbot_control` data source fails with a GraphQL syntax error when querying controls by `type` and `resource` parameters (as opposed to querying by `id` alone).

## Error Message

```
Error: error reading control: graphql: Syntax Error: Expected Name, found :
```

## Root Cause

The bug is in `apiClient/queries.go` at line 640. The `readControlQuery` function incorrectly prefixes all arguments with `id:`, which causes invalid GraphQL syntax when the arguments already include parameter names.

**Current (incorrect) code:**
```go
func readControlQuery(args string) string {
    return fmt.Sprintf(`{
control(id:%s){
    ...
}
}`, args)
}
```

When the data source calls this with `uri: "...", resourceId: "..."`, it generates:
```graphql
control(id:uri: "...", resourceId: "...")
```

This is invalid GraphQL syntax - the `id:` prefix causes the parser to expect a value, but finds `uri:` instead.

## Expected Behavior

The function should pass through the arguments without modification:
```go
func readControlQuery(args string) string {
    return fmt.Sprintf(`{
control(%s){
    ...
}
}`, args)
}
```

This generates valid GraphQL for both query patterns:
- `control(id: "123456")` - when querying by control ID
- `control(uri: "...", resourceId: "...")` - when querying by type and resource

## Steps to Reproduce

1. Use the `turbot_control` data source with `type` and `resource` parameters:
```hcl
data "turbot_control" "check" {
  type     = "tmod:@turbot/aws-s3#/control/types/bucketVersioning"
  resource = "arn:aws:s3:::my-bucket"
}
```

2. Run `terraform plan` or `terraform apply`
3. Observe the GraphQL syntax error

## Impact

This bug prevents the `turbot_control` data source from being used with `type` and `resource` parameters, forcing users to query by `id` only (which requires knowing the control ID beforehand).

## Fix

Change line 640 in `apiClient/queries.go` from:
```go
control(id:%s){
```

to:
```go
control(%s){
```

A PR with this fix will follow shortly.

### PR DESCRIPTION
**Pull request by vkumbha**
## Description

Fixes #233

This PR resolves a GraphQL syntax error that occurs when querying the `turbot_control` data source by `type` and `resource` parameters.

## Changes

- **File**: `apiClient/queries.go`
- **Line**: 640
- **Change**: Removed hardcoded `id:` prefix from the GraphQL query template

### Before
```go
func readControlQuery(args string) string {
    return fmt.Sprintf(`{
control(id:%s){
    ...
}
}`, args)
}
```

**Generated query** (invalid):
```graphql
control(id:uri: "tmod:@turbot/aws-s3#/control/types/bucketVersioning", resourceId: "123456")
```

**Error**: `graphql: Syntax Error: Expected Name, found :`

### After
```go
func readControlQuery(args string) string {
    return fmt.Sprintf(`{
control(%s){
    ...
}
}`, args)
}
```

**Generated queries** (valid):
- By ID: `control(id: "123456")`
- By type & resource: `control(uri: "...", resourceId: "...")`

## Testing

Verified the fix generates valid GraphQL syntax for both query patterns:

```go
// Test with id
args1 := `id: "123456"`
readControlQuery(args1)
// Output: control(id: "123456"){ ... }  ✅

// Test with uri and resourceId  
args2 := `uri: "tmod:@turbot/aws-s3#/control/types/bucketVersioning", resourceId: "375591044411415"`
readControlQuery(args2)
// Output: control(uri: "...", resourceId: "..."){ ... }  ✅
```

## Impact

This fix allows the `turbot_control` data source to work correctly with both query methods:
1. Query by control ID: `id = "123456"`
2. Query by control type and resource: `type = "..." + resource = "..."`

Previously, only method #1 worked. Method #2 resulted in a GraphQL syntax error.

## Checklist

- [x] Code change is minimal and focused
- [x] No changes to SDK versions or dependencies
- [x] Fix validated with test script
- [x] Resolves the reported issue

### CODE REVIEW

File: apiClient/queries.go [hunk 1]
```diff
@@ -637,7 +637,7 @@ func updateSamlDirectoryMutation(properties []interface{}) string {
 // control
 func readControlQuery(args string) string {
 	return fmt.Sprintf(`{
-control(id:%s){
+control(%s){
```
Comment (Subhajit97) [inline apiClient/queries.go:640]: @vkumbha I can see the same query has been used in `resource_turbot_control_mute` resource as well. Did you validate that resource too after making the changes?

Comment (vkumbha) [reply apiClient/queries.go:640]: No, I did not!

**Comment by vkumbha** [comment]
# Terraform Provider Test Results

## Test Environment
- **Terraform Version**: 0.12.31 (x86_64 via Rosetta on Apple Silicon)
- **Provider**: Local build of terraform-provider-turbot
- **Turbot Profile**: `punisher`
- **Test Date**: January 21, 2026

## Test Configuration

The test configuration includes:
1. **Data Source**: `turbot_control` (by ID) - Reading control by ID
2. **Data Source**: `turbot_control` (by type and resource) - Reading control by type and resource ID
3. **Resource**: `turbot_control_mute` - Creating a control mute

```hcl
data "turbot_control" "test" {
  id = "375591044827212"
}

data "turbot_control" "check" {
  type     = "tmod:@turbot/aws-s3#/control/types/bucketVersioning"
  resource = "375591044411415"
}

resource "turbot_control_mute" "mute_instance_approved" {
  resource     = "arn:aws:s3:::test-venu-bucket-tf"
  control_type = "tmod:@turbot/aws-s3#/control/types/bucketVersioning"
  note         = "Muting the control till alarm/error is resolved."
  to_timestamp = "2026-10-26T06:07:19.652Z"
  until_states = ["ok"]
}
```

## Test Execution

### 1. Terraform Init
```bash
$ TURBOT_PROFILE=punisher terraform init
```
**Result**: ✅ Successfully initialized

### 2. Terraform Plan
```bash
$ TURBOT_PROFILE=punisher terraform plan
```
**Result**: ✅ Plan generated successfully
- Plan: 1 to add, 0 to change, 0 to destroy

### 3. Terraform Apply
```bash
$ TURBOT_PROFILE=punisher terraform apply -auto-approve
```

**Output**:
```
data.turbot_control.test: Refreshing state...
data.turbot_control.check: Refreshing state...
turbot_control_mute.mute_instance_approved: Creating...
turbot_control_mute.mute_instance_approved: Creation complete after 2s [id=375591044827212]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Result**: ✅ **SUCCESS** - All resources and data sources created/read successfully

### 4. Terraform Show (Verification)

**Data Source Results**:

1. **turbot_control.test** (by ID):
```
data "turbot_control" "test" {
    id       = "375591044827212"
    reason   = "Versioning not set correctly to Enabled"
    resource = "375591044411415"
    state    = "muted"
    type     = "tmod:@turbot/aws-s3#/control/types/bucketVersioning"
}
```

2. **turbot_control.check** (by type and resource):
```
data "turbot_control" "check" {
    id       = "375591044827212"
    reason   = "Versioning not set correctly to Enabled"
    resource = "375591044411415"
    state    = "alarm"
    type     = "tmod:@turbot/aws-s3#/control/types/bucketVersioning"
}
```

**Resource Result**:
```
resource "turbot_control_mute" "mute_instance_approved" {
    control_id   = "375591044827212"
    control_type = "tmod:@turbot/aws-s3#/control/types/bucketVersioning"
    id           = "375591044827212"
    note         = "Muting the control till alarm/error is resolved."
    resource     = "arn:aws:s3:::test-venu-bucket-tf"
    state        = "muted"
    to_timestamp = "2026-10-26T06:07:19.652Z"
    until_states = ["ok"]
}
```

## Test Summary

✅ **All tests passed successfully**

- ✅ Provider initialization works correctly
- ✅ Data source `turbot_control` (by ID) successfully reads control information
- ✅ Data source `turbot_control` (by type and resource) successfully reads control information
- ✅ Resource `turbot_control_mute` successfully creates control mutes
- ✅ Provider correctly uses `TURBOT_PROFILE` environment variable
- ✅ Provider communicates with Turbot API successfully
- ✅ Resource state is correctly managed
- ✅ Both data source query methods work correctly

File: apiClient/queries.go (hunk 1 above)
Comment (vkumbha) [reply apiClient/queries.go:640]: @Subhajit97 tested the resource_turbot_control_mute resource and updated the results below.

**Review by Subhajit97 — APPROVED** [review]
