### PR TITLE
[BUG]r/turbot_google_directory: hosted_name argument always show a update on successful creation of resource. Closes #75

### LINKED ISSUE #75: [BUG]r/turbot_google_directory: hosted_name argument always show a update on successful creation of resource

### LINKED ISSUE #76: [BUG]r/turbot_google_directory: client_secret was not getting encrypted

### PR DESCRIPTION
**Pull request by RupeshPatil20**

### CODE REVIEW

File: turbot/resource_turbot_google_directory.go [hunk 1]
```diff
@@ -74,11 +66,23 @@ func resourceGoogleDirectory() *schema.Resource {
...
+			"description": {
+				Type:     schema.TypeString,
+				Optional: true,
+			},
 			"pgp_key": {
 				Type:     schema.TypeString,
 				ForceNew: true,
 				Optional: true,
 			},
+			"directory_type": {
```
Comment (RupeshPatil20) [inline turbot/resource_turbot_google_directory.go:78]: we removed `directory_type` in our previous commits. Was it intentional or a mistake? Need some thoughts.
