### PR TITLE
Fix turbot_resource import which forces deletion of existing configurations. Closes #62

### LINKED ISSUE #62: Fix turbot_resource import which forces deletion of existing configurations

### PR DESCRIPTION
**Pull request by RupeshPatil20**
…ations. Closes#62

### CODE REVIEW

File: apiClient/resource.go [hunk 1]
```diff
@@ -165,6 +165,10 @@ func (client *Client) AssignResourceResults(responseData interface{}, properties
 	if err := mapstructure.Decode(responseData.(map[string]interface{})["turbot"], &resource.Turbot); err != nil {
 		return nil, err
 	}
+	// convert type property
+	if err := mapstructure.Decode(responseData.(map[string]interface{})["type"], &resource.Type); err != nil {
```
Comment (kaidaguerre) [inline apiClient/resource.go]: what is this doing?
