### PR TITLE
[Fix]: Replace getExists call with getOk to fetch current state and SET attributes based on read API. Closes #124

### LINKED ISSUE #124: [Fix]: Replace getExists call with getOk to fetch current state and SET attributes based on read API

### PR DESCRIPTION
**Pull request by RupeshPatil20**
Closes #124

### CODE REVIEW

File: turbot/resource_turbot_resource.go [hunk 1]
```diff
@@ -387,7 +392,13 @@ func markPropertiesForDeletion(d *schema.ResourceData, key string) (map[string]i
 			// set keys of old content to `nil` in new content
 			// any property which doesn't exist in config is set to nil
 			if _, ok := oldContent[key.(string)]; ok {
-				newContent[key.(string)] = nil
+				if getResourceType(d.Get("type").(string)) == "folder" {
```
Comment (kaidaguerre) [inline turbot/resource_turbot_resource.go]: add comment for folder special case handling

Comment (kaidaguerre) [reply turbot/resource_turbot_resource.go]: I think I would actually change this to something like


```
	// NOTE: for folder we cannot currently delete the description property
	shouldDelete := !(getResourceType(d.Get("type").(string)) == "folder" &&  key == "description")
	if _, ok := oldContent[key.(string)]; ok && shouldDelete {
		newContent[key.(string)] = nil
	}

```

**Review by kaidaguerre — CHANGES_REQUESTED** [review]
