### PR TITLE
Fix policy setting import which forces deletion of existing configurations. Closes #57

### LINKED ISSUE #57: Fix policy setting import which forces deletion of existing configurations
**Steps** -

- create turbot policy setting, delete the state file.
- import the policy setting via `terraform import`

**Actual Behaviour** -
```
-/+ resource "turbot_policy_setting" "s3_bucket_versioning" {
      ~ id                           = "184901232412638" -> (known after apply)
        precedence                   = "REQUIRED"
      + resource                     = "184901229298682"
      ~ resource_akas                = [
          - "184901229298682",
        ] -> (known after apply)
      + type                         = "tmod:@turbot/aws-s3#/policy/types/bucketVersioning" # forces replacement
        value                        = "Check: Enabled"
      + value_key_fingerprint        = (known after apply)
      ~ value_source                 = <<~EOT
            'Check: Enabled'
        EOT -> (known after apply)
      + value_source_key_fingerprint = (known after apply)
      + value_source_used            = (known after apply)
    }
Plan: 1 to add, 0 to change, 1 to destroy.
```
**Expected Behaviour** -
```
No changes. Infrastructure is up-to-date.
```

### PR DESCRIPTION
**Pull request by RupeshPatil20**

### CODE REVIEW

File: apiClient/queries.go [hunk 1]
```diff
@@ -78,28 +81,34 @@ func createPolicySettingMutation() string {
...
-	input
-	note
-	validFromTimestamp
-	validToTimestamp
-	turbot {
-		id
-		resourceId
+	policySetting(id:"%s") {
+		type {
+    		uri
```
Comment (kaidaguerre) [inline apiClient/queries.go]: formatting/tabbing wrong?

File: apiClient/types.go [hunk 2]
```diff
@@ -83,6 +83,9 @@ type FindPolicySettingResponse struct {
 }
 
 type PolicySetting struct {
+	Type struct {
+		Uri interface{}
```
Comment (kaidaguerre) [inline apiClient/types.go]: does this need to be interface?
