### PR TITLE
Fix turbot_google_directory import forces deletion of exiting configurations. Closes #66

### LINKED ISSUE #66: Fix turbot_google_directory import forces deletion of exiting configurations

### PR DESCRIPTION
**Pull request by RupeshPatil20**
…rations. Closes #66

### CODE REVIEW

File: turbot/resource_turbot_google_directory.go [hunk 1]
```diff
@@ -229,7 +229,10 @@ func storeClientSecret(d *schema.ResourceData, clientSecret string) error {
 }
 
 // if the value is encrypted we cannot perform drift detection - suppress the diff if a pgp key has been specified
-func suppressIfPgpKeyPresent(k, old, new string, d *schema.ResourceData) bool {
-	_, keyPresent := d.GetOk("pgp_key")
-	return old != "" && keyPresent
+func suppressIfClientSecretPresent(k, old, new string, d *schema.ResourceData) bool {
+	// Read returns null value for client_secret, we suppress the diff on old (config) and new (state file)
```
Comment (kaidaguerre) [inline turbot/resource_turbot_google_directory.go]: // We do not read back client secret so suppress diff caused by empty value

File: turbot/resource_turbot_google_directory.go [hunk 2]
```diff
@@ -229,7 +229,10 @@ func storeClientSecret(d *schema.ResourceData, clientSecret string) error {
 }
 
 // if the value is encrypted we cannot perform drift detection - suppress the diff if a pgp key has been specified
```
Comment (kaidaguerre) [inline turbot/resource_turbot_google_directory.go]: remove
